=== Hejsel/Dataintergration/XML-skemaer/opgave1/client/starwars-skema.dtd
<!ELEMENT starwars (karakter+)>
<!ELEMENT karakter (navn, art, hjemplanet, rolle, vaaben)>
<!ELEMENT navn (#PCDATA)>
<!ELEMENT art (#PCDATA)>
<!ELEMENT hjemplanet (#PCDATA)>
<!ELEMENT rolle (#PCDATA)>
<!ELEMENT vaaben (#PCDATA)>

=== Hejsel/Dataintergration/XML-skemaer/opgave1/client/starwars-data.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE starwars SYSTEM "starwars-skema.dtd">
<starwars>
    <karakter>
        <navn>Luke Skywalker</navn>
        <art>Menneske</art>
        <hjemplanet>Tatooine</hjemplanet>
        <rolle>Jedi</rolle>
        <vaaben>Lysværd</vaaben>
    </karakter>
    <karakter>
        <navn>Darth Vader</navn>
        <art>Menneske</art>
        <hjemplanet>Tatooine</hjemplanet>
        <rolle>Sith Lord</rolle>
        <vaaben>Lysværd</vaaben>
    </karakter>
    <karakter>
        <navn>Yoda</navn>
        <art>Ukendt</art>
        <hjemplanet>Ukendt</hjemplanet>
        <rolle>Jedi Mester</rolle>
        <vaaben>Lysværd</vaaben>
    </karakter>
    <karakter>
        <navn>Han Solo</navn>
        <art>Menneske</art>
        <hjemplanet>Corellia</hjemplanet>
        <rolle>Smugler</rolle>
        <vaaben>Blaster</vaaben>
    </karakter>
</starwars>
